'use strict';

/*
 * FREEzzzGames
 * Production manager
 *
 * Calculates production generated by active buildings.
 * This module only handles production calculations.
 * Economy state, buildings state and server validation
 * are handled by separate modules.
 */

const DEFAULT_PRODUCTION = Object.freeze({
    farm: 1,
    workshop: 2,
    stadium: 3,
    studio: 4,
    shopping_center: 5
});

class Production {
    constructor(options = {}) {
        this.productionRates = {
            ...DEFAULT_PRODUCTION,
            ...(options.productionRates || {})
        };
    }

    getRate(type) {
        if (
            typeof type !== 'string' ||
            !Object.prototype.hasOwnProperty.call(
                this.productionRates,
                type
            )
        ) {
            return 0;
        }

        return this.productionRates[type];
    }

    calculateBuildingProduction(building) {
        if (
            !building ||
            typeof building !== 'object' ||
            building.active === false ||
            !Number.isFinite(building.level) ||
            building.level < 1
        ) {
            return 0;
        }

        const rate = this.getRate(building.type);

        if (rate <= 0) {
            return 0;
        }

        return rate * building.level;
    }

    calculate(buildings = []) {
        if (!Array.isArray(buildings)) {
            return 0;
        }

        return buildings.reduce(
            (total, building) =>
                total + this.calculateBuildingProduction(building),
            0
        );
    }

    calculatePerSecond(buildings = []) {
        return this.calculate(buildings);
    }

    getRates() {
        return {
            ...this.productionRates
        };
    }

    setRate(type, rate) {
        if (
            typeof type !== 'string' ||
            !Number.isFinite(rate) ||
            rate < 0
        ) {
            return false;
        }

        this.productionRates[type] = rate;

        return true;
    }

    resetRates() {
        this.productionRates = {
            ...DEFAULT_PRODUCTION
        };

        return this.getRates();
    }
}

const production = new Production();

export {
    Production,
    DEFAULT_PRODUCTION
};

export default production;